# Generated by Django 4.2.4 on 2023-08-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riva_api', '0003_seller_username_alter_seller_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
