# Generated by Django 4.2.4 on 2023-09-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riva_api', '0007_alter_inventory_image_alter_seller_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
    ]
