version: '3.10'

services:
  db:
    container_name: riva-api-db
    image: postgres:latest
    volumes: 
      - ./data/db:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_DB=ubah_menjadi_nama_database_anda
      - POSTGRES_USER=ubah_menjadi_user_database_anda
      - POSTGRES_PASSWORD=ubah_menjadi_password_database_anda
    
  app:
    container_name: riva-api
    command: sh -c "python manage.prod.py runserver 0.0.0.0:8000"
    build: 
      context: "."
      dockerfile: Dockerfile
    image: riva-api
    volumes:
      - .:/app
    ports:
      - 9001:8000
    environment:
      - SECRET_KEY=ubah_menjadi_secret_key__anda
      - POSTGRES_DB=aubah_menjadi_nama_database_andapi
      - POSTGRES_USER=ubah_menjadi_user_database_anda
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    